Music portal/Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Music_portal.Filters;
using Music_portal.Models;
using Music_portal.Repository;
using System.Diagnostics;

namespace Music_portal.Controllers
{
    [Culture]
    public class GenreController : Controller
    {
        
        IGenreRepository repo;

        public GenreController(IGenreRepository r)
        {
            repo = r;
        }

        public async Task<IActionResult> Genres()
        {
            var model = await repo.GetGenreList();
            return View(model);
        }

        public IActionResult CreateGenre()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateGenre([Bind("Id,Name")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                await repo.CreateGenre(genre);
                await repo.Save();
                return RedirectToAction(nameof(Genres));
            }
            return View(genre);
        }
        public async Task<IActionResult> EditGenre(int? id)
        {
            if (id == null || await repo.GetGenreList() == null)
            {
                return NotFound();
            }
            var genre = await repo.GetGenre((int)id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditGenre(int id, [Bind("Id,Name,Songs")] Genre genre)
        {
            if (id != genre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    repo.Update(genre);
                    await repo.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await GenreExists(genre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Genres));
            }
            return View(genre);
        }

        private async Task<bool> GenreExists(int id)
        {
            List<Genre> list = await repo.GetGenreList();
            return (list?.Any(e => e.Id == id)).GetValueOrDefault();
        }

		public async Task<IActionResult> DeleteGenre(int? id)
		{
			if (id == null || await repo.GetGenreList() == null)
			{
				return NotFound();
			}

			var genre = await repo.GetGenre((int)id);
			if (genre == null)
			{
				return NotFound();
			}

			return View(genre);
		}

		[HttpPost, ActionName("DeleteGenre")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (await repo.GetGenreList() == null)
			{
				return Problem("Entity set 'ClassContext.Genres'  is null.");
			}
			var genre = await repo.GetGenre(id);
			if (genre != null)
			{
				await repo.Delete(id);
			}
			await repo.Save();
			return RedirectToAction(nameof(Genres));
		}

	}
}

Music portal/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Music_portal.Models;
using Music_portal.Repository;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Music_portal.Filters;
using System.Linq;
using Microsoft.IdentityModel.Tokens;
using static System.Net.Mime.MediaTypeNames;

namespace Music_portal.Controllers
{
    [Culture]
    public class HomeController : Controller
    {
        
        ISongRepository repo;
        IGenreRepository gRepo;
        ISingerRepository sRepo;
        IUserRepository userRepo;
        IWebHostEnvironment _appEnvironment;

        public HomeController(ISongRepository r, IGenreRepository gr, ISingerRepository sr, IUserRepository ur, IWebHostEnvironment appEnvironment)
        {
            repo = r;
            gRepo = gr;
            sRepo = sr;
			userRepo = ur;
			_appEnvironment =appEnvironment;
        }

        public async Task<IActionResult> Index(string text, int singer = 0, int genre = 0, int page = 1,
            SortState sortOrder = SortState.TitleAsc )
        {
            HttpContext.Session.SetString("path", Request.Path);
           
            int pageSize = 5;

            //фильтрация
            IQueryable<Song> songs = await repo.GetSongList();

            if (text != null)
            {
                songs = songs.Where(p => p.Title.Contains(text));
            }

            if (genre != 0)
            {
                songs = songs.Where(p => p.GenreId == genre);
            }
            
            if (singer != 0)
            {
                songs = songs.Where(p => p.SingerId == singer);
            }

            // сортировка
            songs = sortOrder switch
            {
                SortState.TitleDesc => songs.OrderByDescending(s => s.Title),
                SortState.SingerAsc => songs.OrderBy(s => s.Singer!.Name),
                SortState.SingerDesc => songs.OrderByDescending(s => s.Singer!.Name),
                SortState.GenreAsc => songs.OrderBy(s => s.Genre!.Name),
                SortState.GenreDesc => songs.OrderByDescending(s => s.Genre!.Name),
                SortState.YearAsc => songs.OrderBy(s => s.Year),
                SortState.YearDesc => songs.OrderByDescending(s => s.Year),                
                _ => songs.OrderBy(s => s.Title),
            };

            // пагинация
            var count = await songs.CountAsync();
            var items = await songs.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            // формируем модель представления
            IndexViewModel viewModel = new IndexViewModel(
                items,
                new PageViewModel(count, page, pageSize),
                new FilterViewModel(await gRepo.GetGenreList(), await sRepo.GetSingerList(), genre, singer),
                new SortViewModel(sortOrder)                            
            ) ;
            return View(viewModel);
        }

        public IActionResult CreateSong()
        {
            HttpContext.Session.SetString("path", Request.Path);
            ViewData["GenreId"] = new SelectList(gRepo.Genres(), "Id", "Name");
            ViewData["SingerId"] = new SelectList(sRepo.Singers(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [RequestSizeLimit(1000000000)]
        public async Task<IActionResult> CreateSong([Bind("Id, Title, Year, PathToFile, GenreId, SingerId, Genre, Singer, User")] Song song, IFormFile uploadedFile)
        {
            if (uploadedFile != null)
            {
                // Путь к папке Files
                string path = "/Songs/" + uploadedFile.FileName; // имя файла

                // Сохраняем файл в папку в каталоге wwwroot
                // Для получения полного пути к каталогу wwwroot применяется свойство WebRootPath объекта IWebHostEnvironment
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream); // копируем файл в поток
                }
                song.PathToFile = path;
            }
            else
            {
                ModelState.AddModelError("", "Please select a file!");
            }
            song.Genre = await gRepo.GetGenre(song.GenreId);
            song.Singer = await sRepo.GetSinger(song.SingerId);

            if (ModelState.IsValid)
            {
                await repo.CreateSong(song);
                await repo.Save();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenreId"] = new SelectList(gRepo.Genres(), "Id", "Name");
            ViewData["SingerId"] = new SelectList(sRepo.Singers(), "Id", "Name");
            return View(song);
        }
        public async Task<IActionResult> EditSong(int? id)
        {
            HttpContext.Session.SetString("path", Request.Path);

            if (id == null || await repo.GetSongList() == null)
            {
                return NotFound();
            }
            var song = await repo.GetSong((int)id);
            if (song == null)
            {
                return NotFound();
            }
            ViewData["GenreId"] = new SelectList(gRepo.Genres(), "Id", "Name");
            ViewData["SingerId"] = new SelectList(sRepo.Singers(), "Id", "Name");
            return View(song);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [RequestSizeLimit(1000000000)]
        public async Task<IActionResult> EditSong(int id, [Bind("Id, Title, Year, PathToFile, GenreId, SingerId")] Song song, IFormFile uploadedFile)
        {
            if (id != song.Id)
            {
                return NotFound();
            }
            if (uploadedFile != null)
            {
                // Путь к папке Files
                string path = "/Songs/" + uploadedFile.FileName; // имя файла

                // Сохраняем файл в папку в каталоге wwwroot
                // Для получения полного пути к каталогу wwwroot применяется свойство WebRootPath объекта IWebHostEnvironment
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream); // копируем файл в поток
                }
                song.PathToFile = path;
            }
            else
            {
                ModelState.AddModelError("", "Please select a file!");
            }
            song.Genre = await gRepo.GetGenre(song.GenreId);
            song.Singer = await sRepo.GetSinger(song.SingerId);

            if (ModelState.IsValid)
            {
                try
                {
                    repo.Update(song);
                    await repo.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await SongExists(song.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenreId"] = new SelectList(gRepo.Genres(), "Id", "Name");
            ViewData["SingerId"] = new SelectList(sRepo.Singers(), "Id", "Name");
            return View(song);
        }

        private async Task<bool> SongExists(int id)
        {
            IQueryable<Song> list = await repo.GetSongList();
            return (list?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public async Task<IActionResult> DeleteSong(int? id)
        {
            HttpContext.Session.SetString("path", Request.Path);

            if (id == null || await repo.GetSongList() == null)
            {
                return NotFound();
            }

            var song = await repo.GetSong((int)id);
            if (song == null)
            {
                return NotFound();
            }
            return View(song);
        }

        [HttpPost, ActionName("DeleteSong")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await repo.GetSongList() == null)
            {
                return Problem("Entity set 'ClassContext.Songs'  is null.");
            }
            var song = await repo.GetSong(id);
            if (song != null)
            {
                await repo.Delete(id);
            }
            await repo.Save();
            return RedirectToAction(nameof(Index));
        }
		public async Task<IActionResult> NewUsers()
		{
            HttpContext.Session.SetString("path", Request.Path);

            var model = await userRepo.GetNewUsersList();
            return View(model);
		}
        public async Task<IActionResult> EditUser(int? id)
        {
            HttpContext.Session.SetString("path", Request.Path);

            if (id == null || await userRepo.GetUserList() == null)
            {
                return NotFound();
            }
            var user = await userRepo.GetUserById((int)id);
            if (user == null)
            {
                return NotFound();
            }            
            return View(user);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser(int id, [Bind("Id,FirstName,LastName,Login,Email,Access")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }
            var us = await userRepo.GetUser(user.Login);
            us.Login = user.Login;
            us.Email = user.Email;
            us.FirstName = user.FirstName;
            us.LastName = user.LastName;
            us.Access = user.Access;
            HttpContext.Session.SetString("Acces", us.Access.ToString());

Music portal/Controllers/SingerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Music_portal.Filters;
using Music_portal.Models;
using Music_portal.Repository;
using System.Diagnostics;

namespace Music_portal.Controllers
{
    [Culture]
    public class SingerController : Controller
    {
        
        ISingerRepository repo;

        public SingerController(ISingerRepository r)
        {
            repo = r;
        }

        public async Task<IActionResult> Singers()
        {
            var model = await repo.GetSingerList();
            return View(model);
        }

        public IActionResult CreateSinger()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateSinger([Bind("Id,Name")] Singer singer)
        {
            if (ModelState.IsValid)
            {
                await repo.CreateSinger(singer);
                await repo.Save();
                return RedirectToAction(nameof(Singers));
            }
            return View(singer);
        }
        public async Task<IActionResult> EditSinger(int? id)
        {
            if (id == null || await repo.GetSingerList() == null)
            {
                return NotFound();
            }
            var singer = await repo.GetSinger((int)id);
            if (singer == null)
            {
                return NotFound();
            }
            return View(singer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditSinger(int id, [Bind("Id,Name,Songs")] Singer singer)
        {
            if (id != singer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    repo.Update(singer);
                    await repo.Save();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await SingerExists(singer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Singers));
            }
            return View(singer);
        }

        private async Task<bool> SingerExists(int id)
        {
            List<Singer> list = await repo.GetSingerList();
            return (list?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        public async Task<IActionResult> DeleteSinger(int? id)
        {
            if (id == null || await repo.GetSingerList() == null)
            {
                return NotFound();
            }

            var singer = await repo.GetSinger((int)id);
            if (singer == null)
            {
                return NotFound();
            }

            return View(singer);
        }

        [HttpPost, ActionName("DeleteSinger")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (await repo.GetSingerList() == null)
            {
                return Problem("Entity set 'ClassContext.Singers'  is null.");
            }
            var singer = await repo.GetSinger(id);
            if (singer!= null)
            {
                await repo.Delete(id);
            }


            await repo.Save();
            return RedirectToAction(nameof(Singers));
        }

    }
}

Music portal/Views/Home/CreateSong.cshtml
@model Music_portal.Models.Song

@{
    ViewData["Title"] = "CreateSong";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <div class="name">@Resources.Resource.AddSong:</div>
    <div>
        <div class="col-md-4">
            <form asp-action="CreateSong" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label class="control-label labl">@Resources.Resource.Title</label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label labl">@Resources.Resource.Year</label>
                    <input asp-for="Year" class="form-control" />
                    <span asp-validation-for="Year" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label labl">@Resources.Resource.Genre</label>
                    <select asp-for="GenreId" class="form-control" asp-items="ViewBag.GenreId"></select>
                </div>
                <div class="form-group">
                    <label class="control-label labl">@Resources.Resource.Singer</label>
                    <select asp-for="SingerId" class="form-control" asp-items="ViewBag.SingerId"></select>
                </div>
                <div class="form-group">
                    <p><label class="control-label labl">@Resources.Resource.PathToFile</label></p>
                    <input class="form-control" type="file" name="uploadedFile" />
                    <span asp-validation-for="PathToFile" class="text-danger"></span>                    
                </div>
                
                <br />
                <div style=" display:flex">
                    <div class=" but">
                        <input class="sub" type="submit" value="@Resources.Resource.Save" />
                    </div>
                    <div class="but">
                        <a asp-action="Index" class="link">@Resources.Resource.BackToList</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
   

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Music portal/Views/Home/DeleteSong.cshtml
@model Music_portal.Models.Song

@{
    ViewData["Title"] = "DeleteSong";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="name">@Resources.Resource.DeleteSong:</div>

<h3 class="del">@Resources.Resource.DeleteConfirm</h3>
<br />
<div>
    <h4 class="del">@Resources.Resource.Song:</h4>
        <div class = "del">
            @Html.DisplayFor(model => model.Title)
        </div>
    <br />
    <form asp-action="DeleteSong">
        <input type="hidden" asp-for="Id" />        
        <div style=" display:flex">
            <div class=" but">
                <input class="sub" type="submit" value="@Resources.Resource.Delete" />
            </div>
            <div class="but">
                <a asp-action="Index" class="link">@Resources.Resource.BackToList</a>
            </div>
        </div>    
    </form>
</div>

Music portal/Views/Home/DeleteUser.cshtml
@model Music_portal.Models.User

@{
    ViewData["Title"] = "DeleteUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="name">@Resources.Resource.DeleteUser:</div>

<h3 class="del">@Resources.Resource.DeleteUsConfirm</h3>
<br />
<div>
    <h4 class="del">User:</h4>
        <div class = "del">
            @Html.DisplayFor(model => model.Login)
        </div>
    <br />
    <form asp-action="DeleteUser">
        <input type="hidden" asp-for="Id" />        
        <div style=" display:flex">
            <div class=" but">
                <input class="sub" type="submit" value="Delete" />
            </div>
            <div class="but">
                <a asp-action="NewUsers" class="link">Back to the list</a>
            </div>
        </div>    
    </form>
</div>

Music portal/Views/Home/EditSong.cshtml
@model Music_portal.Models.Song

@{
    ViewData["Title"] = "EditSong";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <div class="name">@Resources.Resource.EditSong:</div>
    <div>
        <div class="col-md-4">
            <form asp-action="EditSong" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                 <input type="hidden" asp-for="Id" /> 
                <div class="form-group">
                    <label class="control-label labl">@Resources.Resource.Title</label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label labl">@Resources.Resource.Year</label>
                    <input asp-for="Year" class="form-control" />
                    <span asp-validation-for="Year" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label labl">@Resources.Resource.Genre</label>
                    <select asp-for="GenreId" class="form-control" asp-items="ViewBag.GenreId"></select>
                </div>
                <div class="form-group">
                    <label class="control-label labl">@Resources.Resource.Singer</label>
                    <select asp-for="SingerId" class="form-control" asp-items="ViewBag.SingerId"></select>
                </div>
                <div class="form-group">
                    <p><label class="control-label labl">@Resources.Resource.PathToFile</label></p>
                    <input class="form-control" type="file" name="uploadedFile" />
                    <span asp-validation-for="PathToFile" class="text-danger"></span>
                </div>
                <br />
                <div style=" display:flex">
                    <div class=" but">
                        <input class="sub" type="submit" value="@Resources.Resource.Save" />
                    </div>
                    <div class="but">
                        <a asp-action="Index" class="link">@Resources.Resource.BackToList</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
   

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Music portal/Views/Home/Index.cshtml
@* @model IEnumerable<Music_portal.Models.Song> *@
@using Music_portal.Models
@model Music_portal.Models.IndexViewModel
@using Music_portal.TagHelpers

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="margin-left: 1100px;" class="search">   
    <form metod ="get" asp-action="Index">
        <input type="text" name="text" placeholder="@Resources.Resource.SearchSong" />
        <button type="submit" name="submit"/>
    </form> 
</div>


@if (Context.Session.GetString("Acces") == "2" || Context.Session.GetString("Login") == "admin")
{ 
    <div style="display: flex; margin-left: 600px;">    
    <div class="but">
            <a class="link" asp-controller="Genre" asp-action="Genres">@Resources.Resource.Genres</a>
    </div>
    <div class="but">
            <a class="link" asp-controller="Singer" asp-action="Singers">@Resources.Resource.Singers</a>
    </div>
    <div class="but">
            <a class="link" asp-controller="Home" asp-action="NewUsers">@Resources.Resource.Users</a>
    </div>
    </div>
 } 

@if (Context.Session.GetString("Acces") == "1" || Context.Session.GetString("Acces") == "2" || Context.Session.GetString("Login") == "admin")
{
    <div>
        <a class="animated-button1" asp-controller="Home" asp-action="CreateSong">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            @Resources.Resource.AddSong
        </a>
    </div>
}

<br />
<form method="get">    
    <div style="display: flex; vertical-align: bottom; margin-left: 95px;">
        <div >
            <label class="control-label labl filtlabl">@Resources.Resource.Singer: </label>
        <select class="form-control filt" name="singer" asp-items="Model.FilterViewModel.Singers"></select>
        </div>
        <div >
            <label class="control-label labl filtlabl">@Resources.Resource.Genre: </label>
        <select class="form-control filt" name="genre" asp-items="Model.FilterViewModel.Genres"></select>
        </div>
        <div class="divbutfilt">
            <input type="submit" class="butfilt" value="@Resources.Resource.Filter" />
        </div>

    </div>
</form>
<br />
<div class="text-center">
    <table class="table">
        <thead>
            <tr>
                <th>
                    <sort-header action="Index" up="@Model.SortViewModel.Up" current="@Model.SortViewModel.Current"
                                 property="@Model.SortViewModel.TitleSort">
                        @Resources.Resource.Title
                    </sort-header>
                    @* <a asp-action="Index"
                       asp-route-sortOrder="@(Model.SortViewModel.TitleSort)"
                       asp-route-position="@(Model.FilterViewModel.SelectedGenre)"
                       asp-route-team="@(Model.FilterViewModel.SelectedSinger)">Title</a> *@
                </th>
                <th>
                    <sort-header action="Index" up="@Model.SortViewModel.Up" current="@Model.SortViewModel.Current"
                                 property="@Model.SortViewModel.SingerSort">
                        @Resources.Resource.Singer
                    </sort-header>
                    @* <a asp-action="Index"
                       asp-route-sortOrder="@(Model.SortViewModel.SingerSort)"
                       asp-route-position="@(Model.FilterViewModel.SelectedGenre)"
                       asp-route-team="@(Model.FilterViewModel.SelectedSinger)">Singer</a> *@
                </th>               
                <th>
                    <sort-header action="Index" up="@Model.SortViewModel.Up" current="@Model.SortViewModel.Current"
                                 property="@Model.SortViewModel.GenreSort">
                        @Resources.Resource.Genre
                    </sort-header>
                    @* <a asp-action="Index"
                       asp-route-sortOrder="@(Model.SortViewModel.GenreSort)"
                       asp-route-position="@(Model.FilterViewModel.SelectedGenre)"
                       asp-route-team="@(Model.FilterViewModel.SelectedSinger)">Genre</a> *@
                </th>
                <th>
                    <sort-header action="Index" up="@Model.SortViewModel.Up" current="@Model.SortViewModel.Current"
                                 property="@Model.SortViewModel.YearSort">
                        @Resources.Resource.Year
                    </sort-header>
                    @* <a asp-action="Index"
                       asp-route-sortOrder="@(Model.SortViewModel.YearSort)"
                       asp-route-position="@(Model.FilterViewModel.SelectedGenre)"
                       asp-route-team="@(Model.FilterViewModel.SelectedSinger)">Year</a> *@
                </th>                
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                @foreach (var item in Model.Songs)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Singer.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Genre.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Year)
                        </td>
                        <td>
                            <div class="audio" id="aud">
                                <audio controls >
                                    <source src = "@Html.DisplayFor(modelItem => item.PathToFile)">
                                </audio>
                            </div>
                        </td>
                       
                            <td>
                            @if (Context.Session.GetString("Login") == "admin")
                            {
                                <a asp-controller="Home" asp-action="EditSong" asp-route-id="@item.Id" class="link">@Resources.Resource.Edit |</a>
                            }                            
                            @if (Context.Session.GetString("Login") == "admin")
                            {
                                <a asp-controller="Home" asp-action="DeleteSong" asp-route-id="@item.Id" class="link">@Resources.Resource.Delete</a>
                            }
                            </td>                        
                </tr> 
            }
        }
        </tbody>
    </table>
    </div>
<page-link page-model="Model.PageViewModel" page-action="Index"
           page-url-singer="@(Model.FilterViewModel.SelectedSinger)"
           page-url-genre="@(Model.FilterViewModel.SelectedGenre)"
           page-url-sortorder="@(Model.SortViewModel.Current)"></page-link>